-- 코드를 입력하세요
-- 생산일자가 2022년 5월인 식품들의 식품 ID, 식품 이름, 총매출을 조회하는 SQL문을 작성
-- 총매출을 기준으로 내림차순 정렬

SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, SUM(FP.PRICE * FO.AMOUNT) as TOTAL_SALES
FROM FOOD_PRODUCT as FP
INNER JOIN FOOD_ORDER as FO on FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 05
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID ASC