-- 코드를 입력하세요
SELECT CATEGORY, PRICE as MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE PRICE = (
    SELECT MAX(PRICE)
    FROM FOOD_PRODUCT as FP
    WHERE FP.CATEGORY = FOOD_PRODUCT.CATEGORY
)
GROUP BY CATEGORY
HAVING CATEGORY = '과자' OR CATEGORY = '국' OR CATEGORY = '김치' OR CATEGORY = '식용유'
ORDER BY PRICE DESC;